# Generated by Django 3.2.7 on 2021-11-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='height',
            new_name='depth',
        ),
    ]
